### ISSUE TITLE
'fold' command fails, but able to query for state

### ISSUE THREAD

**Issue by bauzer714** [kbernhagen/lufah#10]
I have this same script run on some other batch instances and they seem to work but recent ones seem to have this issue. 

I can't see anything that jumps out as why new nodes aren't working. Hoping you can help.

```
lufah -a '.' fold
Error: FahClient('localhost:7396'):'ClientConnection' object has no attribute 'open'
root@1eaeda48d7f942d393b6be187d4c38d000000H:/mnt/batch/tasks/startup/wd/runner/fclient# lufah -a '.' state
{
  "info": {
    "version": "8.3.18",
    "url": "https://v8-3.foldingathome.org/",
    "os": "linux",
    "os_version": "6.5",
    "cpu": "amd64",
    "cpu_brand": "Intel(R) Xeon(R) Platinum 8272CL CPU @ 2.60GHz",
    "cpus": 4,
    "gpus": {},
    "mach_name": "1eaeda48d7f942d393b6be187d4c38d000000H",
    "hostname": "1eaeda48d7f942d393b6be187d4c38d000000H",
    "mode": "Release",
    "revision": "99ae953ee7b1c0b3070161cfcf9150184f76bd96",
    "has_battery": false,
    "on_battery": false,
    "id": "_ZLs1_Sx28zg69MAEEKACtNiSoxvyfYEf1Z3fFXhHMU",
    "account": ""
  },
  "config": {
    //Redacted
  },
  "groups": {
    "": {
      "config": {
        "on_idle": false,
        "on_battery": true,
        "keep_awake": true,
        "paused": true,
        "finish": false,
        "beta": false,
        "key": 0,
        "cpus": 4,
        "gpus": {}
      },
      "wait": "2024-11-24T14:22:00Z"
    }
  },
  "units": []
}
```

**Comment by kbernhagen** [comment]
Thanks for the report.

Workaround is to use `fahctl fold`, which was added in fah v8.4.4.

**Comment by kbernhagen** [comment]
Another workaround:
```sh
uvx --with websockets==12 lufah fold
```
or
```sh
uvx --with websockets==13 lufah fold
```

**Comment by bauzer714** [comment]
> Another workaround:
> 
> ```shell
> uvx --with websockets==12 lufah fold
> ```
> 
> or
> 
> ```shell
> uvx --with websockets==13 lufah fold
> ```

This was helpful and got it folding again.  You mentioned 8.4.4, but my versions seem to be 8.3 still.  

Will defer to you to close or leave open.

**Comment by kbernhagen** [comment]
I think I need to either explicitly use websockets legacy api, or switch to their new asyncio classes.

**Comment by bauzer714** [comment]
Appreciate your work on this. It's remarkably simplified the management headlessly, enabling my automation and monitoring. I'll keep an eye on the repo.

**Comment by kbernhagen** [comment]
Please reopen if bug persists.

**Comment by Ch3wi3** [comment]
I ran into this problem too. I am running FAH on several machines 24/7. On my desktop PC i'd like to let FAH finish and then shutdown the PC. Since FAHClient still does not offer this (in my eyes fundamental) functionality I wrote a Python script for this task using lufah. But for weeks my lufah call `lufah finish` only produces the error from above: `Error: FahClient('127.0.0.1'):'ClientConnection' object has no attribute 'open'` 
The workarounds mentioned here did not help because I can not install uvx (pip throws errors) and fahctl is still not available either. So what can I do to make this work again?

**Comment by kbernhagen** [comment]
Update lufah to 0.8.1

**Comment by Ch3wi3** [comment]
I tried but the make file fails while installing the websockets dependency ( `ERROR: No matching distribution found for windows-curses; platform_system == "Windows"` ) and `pip install lufah` only installs `lufah-0.7.0` :-(

**Comment by kbernhagen** [comment]
Is this on Windows? `windows-curses` is only used for `lufah top`
Did you use `git pull` to update the repo?
You don't actually need the repo nor make.bat

What about `pip install --upgrade lufah` ?

I use `pipx` or `uv tool install`

`make.bat` uses `pipx`

**Comment by Ch3wi3** [comment]
Yes I am using lufah on windows 10 64bit right now.  `pip install --upgrade lufah` only installed 0.7.x sadly... 
```
>pip install --upgrade lufah
Collecting lufah
  Using cached lufah-0.8.1-py3-none-any.whl.metadata (8.0 kB)
Collecting shellingham (from lufah)
  Using cached shellingham-1.5.4-py2.py3-none-any.whl.metadata (3.5 kB)
Collecting typer-slim (from lufah)
  Using cached typer_slim-0.15.1-py3-none-any.whl.metadata (15 kB)
Requirement already satisfied: websockets>=13.0.1 in c:\users\Ch3wi3\appdata\local\programs\python\python313\lib\site-packages (from lufah) (14.1)
INFO: pip is looking at multiple versions of lufah to determine which version is compatible with other requirements. This could take a while.
Collecting lufah
  Using cached lufah-0.8.0-py3-none-any.whl.metadata (8.1 kB)
  Using cached lufah-0.7.0-py3-none-any.whl.metadata (7.0 kB)
Using cached lufah-0.7.0-py3-none-any.whl (32 kB)
Installing collected packages: lufah
Successfully installed lufah-0.7.0
```

**Comment by kbernhagen** [comment]
Odd. Do you have more than one lufah installed?
What `python --version` ?

**Comment by kbernhagen** [comment]
I have not tested beyond python 3.12

**Comment by kbernhagen** [comment]
Can you use lufah 0.7.0 with websockets downgraded to 13.0.1 ?
Maybe try
```
pip uninstall lufah
pip install pipx
pipx ensurepath
pipx install uv
pipx uninstall lufah
uv tool install --with websockets==13.0.1 lufah
lufah --version
```

**Comment by Ch3wi3** [comment]
> Can you use lufah 0.7.0 with websockets downgraded to 13.0.1 ? Maybe try
> 
> ```
> pip uninstall lufah
> pip install pipx
> pipx ensurepath
> pipx install uv
> pipx uninstall lufah
> uv tool install --with websockets==13.0.1 lufah
> lufah --version
> ```

Hey thank you very much! I tried your commands and now its working. `lufah --version`  says I am still running `0.7.0` but now apparently with websockets v13.0.1 because the commands "finsh", "pause" and "fold" are working again.

**Comment by bauzer714** [comment]
I reverted the changes that were mentioned here: https://github.com/kbernhagen/lufah/issues/10#issuecomment-2496415097 and my lufah fold commands have resumed working on new nodes.

Appreciate your efforts @kbernhagen.

**Comment by kbernhagen** [comment]
I’m inclined to remove windows-curses as a required dependency.

**Comment by kbernhagen** [comment]
lufah 0.8.2 is up.
Please upgrade and let me know if it is broken for you.
Thanks!

**Comment by Ch3wi3** [comment]
I pulled the newest repo changes and ran `make install-user` on my windows machine. Now it builds correctly and `>lufah --version` says: `0.8.2`. 

The folding commands pause, finish and fold are working too. 

Thanks for the great work!

**Comment by kbernhagen** [comment]
At least on macOS, uv and pipx use the same directory for the executable. uv will refuse to overwrite a pipx install. So, just saying you might have two lufah installed. Guess it doesn’t matter if 0.8.2 is running.
