### ISSUE TITLE
How to uninstall lufah?

### ISSUE THREAD

**Issue by Korb** [kbernhagen/lufah#5]
The README.md contains instructions on how to install lufah:

> Requirements
> python 3.8 or later
> Install from PyPI
> `pip install lufah`

But there is no instruction on how to remove the script. How to do it and can you add the instruction to README.md?

**Comment by kbernhagen** [comment]
```
pip uninstall lufah
```

If you used `make install-user`
```
pip install pipx
pipx uninstall lufah
```

If you installed with `uv`
```
uv tool uninstall lufah
```
