### ISSUE TITLE
Add explanations of usage examples to README.md

### ISSUE THREAD

**Issue by Korb** [kbernhagen/lufah#6]
Currently, the `Examples` block is as follows:

```
lufah units
lufah -a //rg2 finish
lufah -a other.local state
lufah -a /mygpu1 config cpus 0
lufah config -h
lufah -a host1,host2,host3 units
lufah -a host1,host2,host3 info
```

It would be much easier to get started with the script if the examples were commented like [this](https://github.com/yt-dlp/yt-dlp).

**Comment by kbernhagen** [comment]
I don't understand what you want.
That tool is a thousand times more complex.

The examples I wrote are semi-random things that people I know might use.
It's part of the `--help` output, and is just a string.

I could add more usage blocks easily to the README.
If the help for the commands is unclear, please suggest new text.

If you just want a sentence for each example, I can do that.

If you just use it, things will probably make more sense.

Tell me what things you want an example for.
